// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_r1cZtC6YRynoJjlDOWB2JbrFS-Antsg',
    appId: '1:817062906129:web:e2deb052c70fef8ec1e4b0',
    messagingSenderId: '817062906129',
    projectId: 'ditonton-8e8d3',
    authDomain: 'ditonton-8e8d3.firebaseapp.com',
    storageBucket: 'ditonton-8e8d3.appspot.com',
    measurementId: 'G-KZ9BDRFB2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8P_Sqz8A3DPDrCxj-EfCJ1RrG4ANf8i8',
    appId: '1:817062906129:android:36568a4d69b44740c1e4b0',
    messagingSenderId: '817062906129',
    projectId: 'ditonton-8e8d3',
    storageBucket: 'ditonton-8e8d3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsseqM2HI2Wz1uB8J-4CCntLpwuI81rhM',
    appId: '1:817062906129:ios:cd1d7244c928a5f9c1e4b0',
    messagingSenderId: '817062906129',
    projectId: 'ditonton-8e8d3',
    storageBucket: 'ditonton-8e8d3.appspot.com',
    iosBundleId: 'com.example.dicodingDitonton',
  );
}
